"""allow null for first and last name

Revision ID: 3bd6608e6bf8
Revises: 005959a8d7cb
Create Date: 2025-01-05 16:50:24.889855

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3bd6608e6bf8"
down_revision: Union[str, None] = "005959a8d7cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "user",
        "last_name",
        existing_type=sa.DATE(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "last_name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.DATE(),
        nullable=False,
    )
    op.alter_column("user", "first_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
