"""add foreign key (user.id) to book table

Revision ID: ac4ee9726e5f
Revises: 83907a17d815
Create Date: 2025-02-09 19:44:37.420542

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac4ee9726e5f"
down_revision: Union[str, None] = "83907a17d815"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("book", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "book", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "book", type_="foreignkey")
    op.drop_column("book", "user_id")
    # ### end Alembic commands ###
